spring:
  application:
    name: "Bibliothek"
  datasource:
    # url: "jdbc:h2:mem:bibliothek-db"
    url: "jdbc:h2:file:/tmp/demo"
    driver-class-name: "org.h2.Driver"
    username: "admin"
    password: ""
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true


externalServiceConfig:
  url: "Hallo"
  credentials:
    username: "Welt"
    password: "!"
  parameter:
    - "foo"
    - "bar"
    - "baz"