spring:
  application:
    name: "Bibliothek"
  datasource:
    url: "jdbc:h2:mem:bibliothek-db"
    driver-class-name: "org.h2.Driver"
    username: "admin"
    password: ""
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update