###

GET http://localhost:8080/api/books

###

POST http://localhost:8080/api/book
Content-Type: application/json

  {
    "id": 0,
    "author": "J.R.R. Tolkien",
    "title": "The Hobbit",
    "publisher": "Allen & Unwin",
    "year": 1937,
    "ean": ""
  }